language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - "pip install pep8 coverage coveralls"
  - "pip install -r requirements.txt"
before_script:
  "./pep8.sh"
script:
  "LANGUAGE=en_GB:en coverage run --source=flask_table setup.py test"
after_success:
  coveralls
